name: Test geo symbology packages and playwright integration tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Ensures Node.js version is 20 or higher]

      # Enable Corepack for Yarn v3 support
      - name: Enable Corepack
        run: corepack enable

      # Re- set up Node.js environment with Corepack enabled and cache
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Ensures Node.js version is 20 or higher
          cache: 'yarn' # Caches Yarn dependencies

      # Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install system wide playwright dependencies
        run: npx playwright install --with-deps

      - name: Lint
        run: yarn lint

      - name: Run core tests
        run: yarn turbo run test --filter @onaio/symbology-calc-core

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
